### ISSUE TITLE
Can't modify childlayout

### ISSUE THREAD

**Issue by hella-schu** [richardhj/contao-childlayouts#10]
Contao 4.4.30, contao-childlayouts 1.1.5

After defining a new layout as childlayout it is only possible to choose which areas should have differences to the parentlayout but no possibility to enter those differences.

![kindlayout](https://user-images.githubusercontent.com/1923638/49685792-562ed080-faea-11e8-8404-0a2df568319c.png)

**Comment by GMTeams** [comment]
Same issue here, but not an all sections. Eg "Frontend-Module" is working, also "JavaScript", but "Experten-Einstellungen" is not working. Thx anyway, the extension is exactly what I've searched for.

**Comment by mariaj** [comment]
Had the same issue. The problem is, that the last entry doesn't end with a semicolon and therefore can't be found by the regular expression in the `findLegendInOriginalPalette()` function of the `Helper.php`.

I changed the line 178 from
`preg_match('/(\{(' . $legendName . ')[^\}]*?\})\,(.+?)\;/', Dca::getOriginalPalette(), $matches);`
to
`preg_match('/(\{(' . $legendName . ')[^\}]*?\})\,(.+?)(\;|$)/', Dca::getOriginalPalette(), $matches);`
 and now it works. 

Please fix the bug and update the repository, 
thanks :)

**Comment by mariaj** [comment]
Thank you for the quick update! 
Unfortunately your fix doesn't work, because you used square brackets `[\;$]`. Please change them to round brackets `(\;|$)`. 
Thanks,
Maria

**Comment by richardhj** [comment]
How come? 
It has the same semantics:
square brackets: any character within bracktes
round brackets: grouping of the set (I don't need to group the line ending)

**Comment by mariaj** [comment]
If you use the square brackets the end of line `$` gets interpreted as the character $.
